### ISSUE TITLE
Rozbity zebricek

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#102]
Aktualne zebricek neobsahuje zadna data, verze 02.305

![Image](https://user-images.githubusercontent.com/101713252/194744466-96faf68c-cab6-4a5a-aaff-c10f9d8cc3cd.png)

**Comment by Deli-Sedlackova** [comment]
Edit: Verze 0.2.305 
Mně žebříček funguje, ale vidím v něm beta uživatele, to nevím, jestli je bug, ale přidávám to sem. :D

![Image](https://user-images.githubusercontent.com/98404015/194749339-a5fab094-b668-40b9-92a9-fa1e21fbac15.jpeg)

**Comment by Deli-Sedlackova** [comment]
Neděje se mi, @JanaHej tobě jo? Kdyžtak zavřu

**Comment by JanaHej** [comment]
@Deli-Sedlackova chyba se již neprojevuje, můžeme zavřít
