### ISSUE TITLE
V O zdraví se zobrazuje divný obdelník dole

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#104]
Při načtení sekce O zdraví se začal zobrazovat obdélník vpravo dole napříč všemi sekcemi, viz screenshoty:

![Image](https://user-images.githubusercontent.com/98404015/194751571-e0f65a93-5bf3-4744-91d0-b971a5cd13db.PNG)

![Image](https://user-images.githubusercontent.com/98404015/194751575-dea43203-359c-44a9-b0e7-3d5d8b7e1a8f.PNG)

**Comment by Deli-Sedlackova** [comment]
@Brambora0 a můžeme ho nějak skrývat my v appce?

**Comment by Brambora0** [comment]
@Deli-Sedlackova My v aplikaci s ním nic udělat nemůžeme, na webu by asi šlo nastavit, aby reCapcha nebyla na mobilech (nevím jestli to je chtěné).
