### ISSUE TITLE
PROD: Po odhlaseni se uzivatel nemuze prihlasit zpet do aplikace

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#110]
Uzivatel prosel onboarding zalozil ucet, vytvoril zde novou prohlidku. Pak se odhlasil a uz se needalo prihlasit.

v db vidim account s id 5097, alee aplikacee mi pri pokusu o prihlaseni pise "Uzivatel s timto emailem neexistuje"

verze: 04.18

**Comment by Deli-Sedlackova** [comment]
Verze 0.4.18
Stávající uživatel si po aktualizace aplikace nemůže opětovně přihlásit do appky:
- přihlašuje se skrze appleID (věřím, že si nějakou dobu appku neotevřela)
- uživatel se přihlačuje pod účtem jana.sedlackova@yahoo.com

**Comment by janblahacgi** [comment]
Dořešit DQ (existující duplicity)
