### ISSUE TITLE
Dev: Progress bar nefunguje správně u vlastních prohlídek

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#111]
Verze 0.2.310
Divné chování při zadání a úpravě termínů prohlídky. Zadám prohlídku v onboardingu, upravím termín poslední prohlídky (nový termín prohlídky nemám) a progress bar ukazuje jiný stav prohlídky. Následně po přidání termínu prohlídky progress bar ukazuje správně. Po zrušení termínu je to opět rozházené. Viz klip:

https://user-images.githubusercontent.com/98404015/195601984-9163acdd-8680-4907-88ca-f5dd25368675.MP4

**Comment by KeiShadow** [comment]
@Deli-Sedlackova  prosím tě jaký má být správný výsledek ? :D

**Comment by Deli-Sedlackova** [comment]
@KeiShadow Chování progress baru je tu ve [Figmě](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=5210%3A48815)

**Comment by KeiShadow** [comment]
@Brambora0  koukni do figmy, a zkus to podle toho opravit. :)
