### ISSUE TITLE
Dev: Prohlídky na main screen se neřadí správně

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#112]
Verze 0.2.310

Řazení prohlídek na main screen neodpovídá zadání: 
V sekci BEZ NA PROHLIDKU - radime podle data chronologicky - od nejblizsiho termínu (date, time). Pokud by byly dve a vice prohlidek se stejnym casem, radime nejdrive povinne prohlidky (podle priority) a pak vlastni (abecedne).
V sekci OBJEDNEJ SE se nejdrive seradi prohlídky, které jsou v okně 2 měsíců pro včasné objednání (razeno primarne podle data a sekundarne podle priority u povinnych prohlidek, za nimi abecedne vlastni prohlidky. Za nimi nasleduji prohlidky po terminu vcasneho objednani, serazeni podle priority (povinne) a pak abecedne vlastni prohlidky.
DALŠÍ PROHLÍDKY - tato sekce by mela byt beze zmen (vlastni prohlidky zde nejsou)
PŘIPOMENEME TI PROHLÍDKU - razeno podle data chronologicky, a sekundarne podle priority nejdříve (povinne prohlidky) a za nimi abecedne vlastni.
PŘIPOMENEME TI OBJEDNÁNÍ - razeno podle data chronologicky, a sekundarne podle priority nejdříve (povinne prohlidky) a za nimi abecedne vlastni.

- [ ] Aktuálně se některé prohlídky, které mám objednané na 13.11. řadí do "Běž na prohlídku" a některé do "Připomeneme ti prohlídku", viz klip.
- [ ] Také se v sekci "objednej se" i přes to, že mám všechny prohlídky s posledním termínem "nevím", tak se mi povinná řadí až po vlastních, viz tentýž klip.

https://user-images.githubusercontent.com/98404015/195623643-48593045-96ae-4a92-990e-a619b9c5cdcd.MP4

- [ ] V sekci "Připomenu ti prohlídku" se mi prohlídky ve stejný čas neřadí správně abecedně, viz foto:

![Image](https://user-images.githubusercontent.com/98404015/195623780-30971759-6b45-4b7d-a7f5-8289da72764f.PNG)

- [ ] V sekci připomenu ti objednání mám první povinnou prohlídku a ani nejsou seřazené vlastní prohlídky chronologicky, viz foto: 

![Image](https://user-images.githubusercontent.com/98404015/195623725-7a39f300-c07a-4e54-8638-0ec7e4550a11.PNG)

**Comment by KeiShadow** [comment]
Bude k otestování v nové verzi: 02313
