### ISSUE TITLE
Dev: Při rozkliku prohlídek z main screen se zobrazují v detailu jiné

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#114]
Verze 0.2.311
V případě, že na main screen rozkliknu prohlídky ze sekce "Další prohlídky", tedy povinné prohlídky na které mám nárok ale neudělala jsem onboarding, tak se mi v detailu rozklikává jiný onboarding než na který klikám, viz klipy: první je muž 50+, druhé je žena 50+

https://user-images.githubusercontent.com/98404015/195853463-25d0fe53-1336-4b29-a973-3889d1db26fd.MP4

https://user-images.githubusercontent.com/98404015/195853486-4a497527-4b11-42be-ab5a-798bfeb205de.MP4

**Comment by JanaHej** [comment]
Stejna chyba jako u Deli, ale ne u vsech prohlidek viz video https://user-images.githubusercontent.com/101713252/195855765-23d58883-7f3b-4d0e-99ac-cf45a8fd2e15.MOV
