### ISSUE TITLE
Při zvětšení písma v telefonu se nejde dostat ze screen s avatarem

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#120]
Pokud má uživatel zvětšené písmo na telefonu, tak po onboardingu se nedostane přes screen avatara do aplikace. Podobná věc se děje v případě, že si z Prevence rozklikne avatara, už se nedostane zpět, musí aplikaci vypnout a zapnout.

**Comment by Brambora0** [comment]
@Deli-Sedlackova mě to funguje, nevíme o tom nějaké detaily (zkoušel jsem to na Androidu 11 a 13, je možné, že je to rozbité třeba jen u IOS nebo u jiných verzích)?

![Screenshot_20221022-173129_[dev] Preventivka.png](https://user-images.githubusercontent.com/58693944/197347751-a918236f-cb83-43d6-8fba-ffc30b97211c.png)

**Comment by Brambora0** [comment]
Zkoušel jsem to ještě na různě velkých obrazovkách a pokud je hodně malá obrazovka nebo hodně velké písmo, tak se na nich některé prvky nezobrazí, překryjí, to opravím. Ale ta obrazovka s avatarem mi připadá jako hodně odolná proti velikosti písma/malé obrazovce @Deli-Sedlackova potřeboval bych k tomu informaci o typu zařízení, velikosti displeje a ideálně jak má písmo zvětšené a jestli nemá zapnuté nějaké usnadnění, protože mě se to nasimulovat nedaří (zkoušel jsem to na různých velikostech).

**Comment by Deli-Sedlackova** [comment]
@Brambora0 nene, správné chování je, že pokud na té screen není vidět náš button "Preventivní prohlídky", tak by měl jít scroll dolů, aby se na něj člověk dostal. Jinak je zaseklý na téhle screen a musí aplikaci ukončit.
