### ISSUE TITLE
Po vytvoření účtu a přihlášení se aplikace nenačítá

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#121]
Verze 0.4.20

Po vytvoření účtu a přihlášení se uživateli místo seznamu prohlídek zobrazuje loader, 0 bodů a aplikace více nenačte. Zařízení ios

![Image](https://user-images.githubusercontent.com/98404015/196928210-f976c964-66e7-42c7-91bf-fddf98dcea93.png)

**Comment by Brambora0** [comment]
Nepodařilo se nasimulovat, @martinCalik vyskytuje se na prod verzi?

**Comment by martinCalik** [comment]
Ahoj @Brambora0, skus to prosim, ale ked to nema doplneny popisok, malo by sa diat, jak na prode, tak na deve.

**Comment by Brambora0** [comment]
Ahoj, @martinCalik zkoušel jsem to, na prod ani dev se mi to nasimulovat nepodařilo. Naposledy se mi tahle chyba stala v září na dev.

**Comment by smolikjacgi** [comment]
@martinCalik @Deli-Sedlackova Mame prosim info, ze je issue aktualni a ze se nejedna o pohrobek treba z dob performance issues na be?

**Comment by martinCalik** [comment]
Ak sa nepodarilo nasimulovať, tak to môžeme uzavrieť. Jedine, že by mala @Deli-Sedlackova ešte doplňujúce info.
