### ISSUE TITLE
Uživateli se ukazuje, že appka není dostupná

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#123]
Na Google play se uživatelce zobrazuje, že "aplikace Preventivka není dostupná v mé zemi". S žádnými jinými aplikacemi nemá problém a je v České republice. Připojuji screenshoty zařízení i store: 

![Image](https://user-images.githubusercontent.com/98404015/197767922-c20f432c-dee8-4047-a7b7-e91070a7ff8c.png)

![Image](https://user-images.githubusercontent.com/98404015/197767930-5504ccc8-59b5-4539-81bb-148cea6ebd49.png)

**Comment by Brambora0** [comment]
Na screenshotu z Google play je vidět "age rating" ESRB pro severní ameriku (to E s popiskem everyone), v Evropě by se mělo zobrazovat PEGI hodnocení. Je možné, že uživatelka má nastavenou zemi v severní americe a Preventivka je jen pro české/evropské uživatele. Ostatní aplikace by měli jít, protože většina aplikací je dělaná pro celosvětové použití.
