### ISSUE TITLE
Nedostatečná kapacita serveru

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#124]
Počkat na výstupy z #75 
[#73](https://github.com/Loono-cz/loono-tasks/issues/73)

**Comment by jakubvoves** [comment]
pokud se v BE neupraví konfigurace pro napojení na JMX nedokážeme určit, že se jedná o nedostatečnou kapacitu serveru. zatím tomu nic nenasvědčuje
