### ISSUE TITLE
Prod: Nelze potvrdit absolvované samovyšetření

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#131]
Verze 0.4.20
Po provedení samovyšetření prsou v příslušném intervalu při rozkliku " Vyšetřila jsem se" se screen zasekne na "Je to v pořádku/Něco jsem si našla" a nereaguje. Uživatelka [kristyna.martinakova@loono.cz](mailto:kristyna.martinakova@loono.cz) Uživatelka si poslední vyšetření provedla 21.9., takže správně by neměla mít možnost samovyšetření už provést (po termínu). V databázi se jí samovyšetření zobrazuje jako "planned" a ne "missed". Viz klip:

https://user-images.githubusercontent.com/98404015/198296157-879f6a76-fdca-4f7e-b736-c98b6e9dc8c2.MP4

**Comment by Deli-Sedlackova** [comment]
Edit. Toto se děje i u samovyšetření varlat (a pravděpodobně i kůže?) v jakém je to stavu? @StepanDrozdek @Brambora0

**Comment by janblahacgi** [comment]
Možno ověřit 21.1.
Kolika lidí se tento problém týká celkově? @StepanDrozdek

**Comment by Deli-Sedlackova** [comment]
Stále mi to na produkci neběží, jsem tam jako adela.sedlackova@gmail.com, vyšetření mám provést 7.1., což už mi dnes umožňuje, viz video: 


https://user-images.githubusercontent.com/98404015/210583138-bf0e25eb-1121-4e2b-b50e-a458d28362a2.MP4

**Comment by Deli-Sedlackova** [comment]
Mně už to funguje @JanaHej prosím, otestuješ?

**Comment by JanaHej** [comment]
@Deli-Sedlackova chyba se již neprojevuje, můžeme zavřít
