### ISSUE TITLE
Přidání prohlídky - výběr typu vyšetření - FE + uprava ciselniku

### ISSUE THREAD

**Issue by jana-pajdlhauserova** [Loono-cz/loono-tasks#134]
Prosím upraviť overlay pre výber typu vyšetrenia pri pridávaní vlastnej prehliadky.

1. Upraviť číselník a odstrániť možnost "Zobrazovací metody"
2. Upraviť text titlu a pridať pod title popisek - [viz  https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=16211%3A506817](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=16619%3A222463)

**Comment by smolikjacgi** [comment]
0.2.332
