### ISSUE TITLE
LOON-662 Nový účet - apple login našeptání jména nefunguje

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#14]
The first letter of the name must be a capital letter, not lower case.

Fill in the email automatically from the apple account.

@Matěj Žídek tady našeptávání mi funguje. Problém tady mám u toho, když si chci vyplnit jméno ručně místo toho, co se mi vyplnilo, tak tam stále nemám první písmeno velké, ale malé

**Comment by Deli-Sedlackova** [comment]
Našeptávání emailu i jména hotovo, nicméně stále ukazuje malé písmeno místo kapitálky

**Comment by smolikjacgi** [comment]
@Deli-Sedlackova @JanaHej 
Prosim o upresneni issue, popr. uzavrit.
Stav nyni: pri registraci pres AppleId je nabidnuta prezdivka (jmeno s velkym pocatecnim pismenem) a pote email z appleId
