### ISSUE TITLE
LOON-658 Najít lékaře: Search by address does not search when the číslo popisné is filled in

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#15]
Search by address does not search when číslo popisné is filled in

Expected: The search always shows the street that matches the description even when the číslo popisné is filled in.

![Image](https://user-images.githubusercontent.com/101713252/176044230-bb23a78b-3608-49b2-8d0c-224ce3d1cc56.png)

![Image](https://user-images.githubusercontent.com/101713252/176044244-a1345b8a-5035-42a1-8bb2-b089e047c181.PNG)

**Comment by Deli-Sedlackova** [comment]
Stále mi to nefunguje, v případě že do dev appky zadám číslo popisné k ulici, tak mi aplikace přestane vyhledávat, stejně jako je uvedené v popisu a screenshotech výše.

**Comment by Brambora0** [comment]
Je to na pull requestu (https://github.com/Loono-cz/loono/pull/375)
