### ISSUE TITLE
Přidat do Firebase konverze iOS

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#150]
Aktuálně jsou v produkční Firebase zapnuté konverze pouze na Android. Pro účely marketingu a analytik bychom potřebovali přidat i konverze na iOS. Posílám zprávu od naší kampaň manažerky:
" V Google Ads, keď si nastavujem konverznú akciu, na ktorú smerujem kampane, si pre Android veľmi jednoducho nastavím stiahnutie apky z Google Play. Pre iOS to musím nastaviť, aby sa tieto dáta ťahali z Firebase. Avšak, keď si rozkliknem konverzné možnosti, ktoré mi Firebase ponúka, vidím len konverzie pre Android. Konverzie pre iOS teda vôbec nevidím."

![Image](https://user-images.githubusercontent.com/98404015/207008599-6dc4a575-337a-4b77-842a-af5cb8c303d9.png)

**Comment by smolikjacgi** [comment]
![Image](https://user-images.githubusercontent.com/108390754/212303521-80b415ed-aa83-41fe-b948-3b167aabd73a.png)
