### ISSUE TITLE
Problémy s Dev verzí v Appstore

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#153]
We identified one or more issues with a recent delivery for your app, "[dev] Preventivka" 0.2.328 (20328). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Runner.app” bundle should contain a NSLocationAlwaysAndWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

**Comment by smolikjacgi** [comment]
0.2.329
