### ISSUE TITLE
Prod: Absolvovaná jednorázová prohlídka nezmizí

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#154]
Po uplynutí intervalu vlastní jednorázové prohlídky je prohlídka stále na main screen aniž by zmizela, viz screenshot.
(uživatel adela.sedlackova@gmail.com) 

![Image](https://user-images.githubusercontent.com/98404015/210582544-1ebcb7da-8658-437e-aff9-10ea89e6a11c.PNG)

**Comment by StepanDrozdek** [comment]
@Deli-Sedlackova Tahle prohlídka je na dnešek 12:00, měla by být tedy potvrzena "denním taskem" dnes v noci (v noci z 4.1 na 5.1) - zatím ji vidíš jelikož v době denního tasku (tedy dnes ve 3 ráno), tahle prohlídka nebyla v minulosti, ale v budoucnosti

**Comment by Deli-Sedlackova** [comment]
Zmizela, díík!
