### ISSUE TITLE
LOON-657 O Zdraví - Objevit vše má špatnou barvu

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#16]
“Objevit vše” má špatnou barvu
Nadpis “Prevence uzdraví má špatný font size“

![Image](https://user-images.githubusercontent.com/101713252/176044509-5ef3202a-7fd4-4187-b796-6a18a6063459.png)

![Image](https://user-images.githubusercontent.com/101713252/176044516-31373266-1928-49ea-b486-24001ba866d9.PNG)

**Comment by ulcdenis** [comment]
Celá tato stránka je web view, takže bude potřeba tyto změny provést na webu.

**Comment by Deli-Sedlackova** [comment]
Předám na webeditorku
