### ISSUE TITLE
LOON-642 O zdravi – chyba sharing button

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#18]
Figma priklad https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=8882%3A177994

![Image](https://user-images.githubusercontent.com/101713252/176045025-b6c88c9d-c1a7-4b72-932c-e23efd6deb01.png)

**Comment by smolikjacgi** [comment]
@JanaHej prosim o update Figmy/issue
