### ISSUE TITLE
LOON-631 O zdravi – rozbity footer

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#22]
Apple iPhone 13 mini, iOS 15.4.1

![Image](https://user-images.githubusercontent.com/101713252/176046546-f8b8f3af-41ba-48a1-bfd9-c57f444d85bc.png)

![Image](https://user-images.githubusercontent.com/101713252/176046549-63290463-b1d9-47d6-ac1b-81ec39c7cb95.png)

**Comment by smolikjacgi** [comment]
@JanaHej jedna se o webview, v app nemuzeme upravit

**Comment by JanaHej** [comment]
@Deli-Sedlackova prosim mrkni a pokud je to na web, muzeme zavrit
