### ISSUE TITLE
LOON-624 Pridat success icon k badge v infoboxe

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#23]
ked user ziskal badge, v infoboxe by sa mal ukazovat so success icon

![Image](https://user-images.githubusercontent.com/101713252/176046854-3c1894f0-8e43-4d81-8095-8a1bee7a90d5.png)

**Comment by Brambora0** [comment]
Opraveno v https://github.com/Loono-cz/loono-tasks/issues/6

**Comment by Deli-Sedlackova** [comment]
Toto stále nevidím - ta fajfka se mi nezobrazuje, viz screenshot. Zařízení iPhone 7, verze 0.2.300:


![Image](https://user-images.githubusercontent.com/98404015/193816745-90260590-b3c9-4058-b413-4911d8056a77.jpeg)

**Comment by Brambora0** [comment]
Už by to mělo být opravené.
