### ISSUE TITLE
LOON-633 O zdravi kozmeticke upravy

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#26]
- pohlavne prenosne choroby blog spacing fix
- “Objevit vše” dat ciernou a s ikonkou sipky nepodciarknute
- zjednotit article buttons – rozna vyska dolnej a hornej casti

![Image](https://user-images.githubusercontent.com/101713252/176047714-6bb61de3-83dc-4b29-8538-476e5f4e59f2.png)

![Image](https://user-images.githubusercontent.com/101713252/176047717-b504a66b-e23e-40f4-bf8d-d9c0935561ec.png)

![Image](https://user-images.githubusercontent.com/101713252/176047723-32886ffd-df6a-4f06-8f58-3b741aaa5421.png)

**Comment by smolikjacgi** [comment]
@JanaHej  jedna se o webview, nelze v app upravit

**Comment by JanaHej** [comment]
@Deli-Sedlackova prosim mrkni a pokud je to na web, muzeme zavrit
