### ISSUE TITLE
LOON-630 O zdravi – sipky

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#27]
ked kliknem na sipku v O zdravi, tak sa zacne ukazovat ako neaktivna, pricom sa na nu kliknut da

![Image](https://user-images.githubusercontent.com/101713252/176047910-12481950-9403-4332-8edc-300ed04cb0d3.png)

**Comment by smolikjacgi** [comment]
@JanaHej jedna se o webview, v app nelze upravit

**Comment by JanaHej** [comment]
stale se projevuje @Deli-Sedlackova muzes na  to mrknout? Pokud je to na web, tak tady muzeme zavrit
