### ISSUE TITLE
LOON-690 Nelze potvrdit absolvovanou prohlídku

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#3]
Uživatel po uplynulé preventivní prohlídce nemůže zadat, že ji absolvoval.
Rozkliknutí notifikace mě dostane na obrazovku s datem, kde se mě aplikace ptá "Byl jsi na prohlídce?", ale potvrdit to nikde nejde. Viz screenshot.

![Image](https://user-images.githubusercontent.com/101713252/174896370-794e08bb-a442-4007-9728-01dbc0f996f4.jpg)

**Comment by KeiShadow** [comment]
Tohle by melo byt opravene :D ted jse mto otestoval, tlacitko se zobrazi :D

**Comment by Deli-Sedlackova** [comment]
Opět přišel feedback, že uživateli nejde absolvovaná prohlídka potvrdit: 
"aplikáciu mám rad a donútila ma konečne si v ČR po niekoľkých rokoch nájsť praktického lekára.
Samotnú návštevu však neviem zadať. Nikde nie je tlačidlo “bol som u lekara” stále mi ukazuje iba plánovanú návštevu v minulosti a budúcnosti (snímka obrazovky)."
Verze aplikace 0.3.15
Screenshot: 

![Image](https://user-images.githubusercontent.com/98404015/187149683-7962cc80-6dae-4c2b-bd9f-1fdd6802cf5f.png)
