### ISSUE TITLE
LOON-677 O zdraví se načítá moc dlouho

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#5]
Při otevření sekce se na některých zařízeních O zdraví načítá dlouho (až minutu a půl!). Při brainstormingu jsme došli na tato řešení: Možnost loaderu, cashovat appku, přidat možnost reload:question_mark
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/101713252/174640794-ed8008e1-b79d-4c24-8170-57479cf772e6.gif)
:

**Comment by MartinMacek** [comment]
Tohle se děje pravděpodobně jen na starších zařízeních typu iPhone 7 etc. Na nových zařízeních funguje víceméně okamžitě. Navíc se jedná vždy jen o úvodní načtení, pak už začne fungovat state a cache. Přidával jsem výše přiložený progress načítání ale někde to není dostatečné.
Na androidu se používá hybrid composition, na iOS už jsem nenašel co zrychlovat. Výrazný podíl na tom může mít i samotný výkon webu.

Nevím nakolik je to důležité issue, když se nově předělává celá sekce "o zdraví" do flutteru a napojuje se na loono CMS.

**Comment by smolikjacgi** [comment]
dev note: je issue aktualni? Je problem v app nebo v komunikaci (na strane) s CMS? Jedna se o webview - omezene moznosti

**Comment by JanaHej** [comment]
@Deli-Sedlackova muzes prosim potvrdit, zda je aktualni? me s enepodarilo nasimulovat.
