### ISSUE TITLE
Zrevidovat testovací scénáře

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#53]
V současné době existuje v JIra seznam testovacích scénářů. Cílem tohoto tasku je tyto scénáře zrevidovat a přepsat do githubu, aby byly dostupné.

# Aktualni stav

- seznam testovacich scenaru: https://cesko-digital.atlassian.net/issues/?jql=labels%20%3D%20%22test%22 (35)
- seznam automatizovanych scenaru: https://cesko-digital.atlassian.net/issues/?jql=labels%20%3D%20test-automated (25) (neotestovan kalendar), [https://console.firebase.google.com/u/1/project/loonoapp-dev/testlab/histories/bh.12fd12f9556b7112](https://console.firebase.google.com/u/1/project/loonoapp-dev/testlab/histories/bh.12fd12f9556b7112)
- primarne se testuje FE, na BE existuje zakladni test
- nektere funcionality nejsou testy pokryte (find doctor, explore, BE features (notifikace, cancelace prohlidky atd), zde integracni testy chybi)
- testuje se jen na dev prostredi

? badges, confirmation, feedback, prevence

**Comment by mzdm** [comment]
@JanaHej  FYI GitHUb podporuje i HTML, takže když se v tasku dá v menu vpravo **Export XML** tak se dá pak jednoduše překopírovat kontent v **\<description>**
