### ISSUE TITLE
LOON-621 Badge brzy vyprsi rozbita obrazovka

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#6]
ked som blizko k casu, kedy mi vyprsi badge, tak sa obrazovka ukazuje uplne rozbito
- neukazuju sa caste dotazy
- infobox by mal byt oranzovy
- nemala by sa ukazovat info “za dokoncenou prevetivni prohlidku ziskas…”
- badge je rozpixelovany
- zly stav progres baru

![Image](https://user-images.githubusercontent.com/101713252/176040084-15aa2d24-b7b5-44c8-ad7c-c84a6f05feef.png)

**Comment by Brambora0** [comment]
Při pokusu o simulaci chybové situace jsem narazil na podobnou chybu, která se nastává od 1. zadání datumu prohlídky do zavření aplikace:
- není vidět indikátor vypršení (pokud má být)
- nezobrazuje se text "Běží poslední měsíc platnosti...".
Problém s úplně rozbitou obrazovkou jse mi nepodařilo nasimulovat. @JanaHej při jaké situaci nastal?

**Comment by Brambora0** [comment]
Opravil jsem problém, kterém jsem psal (https://github.com/Loono-cz/loono-tasks/issues/6#issuecomment-1254156648).

- Zakázal jsem, aby se zobrazovaly oba texty najednou ("za dokoncenou prevetivni prohlidku ziskas…", "Běží poslední měsíc platnosti")
- Opravil jsem, aby se zobrazoval indikátor vypršení

Mělo by to fungovat i u 1. problému.

**Comment by Brambora0** [comment]
Aby badge nebyly rozpixelované je potřeba změnit jejich assety z .png na .svg

**Comment by Deli-Sedlackova** [comment]
@Brambora0 vše super až na:

- [ ] stále mám ten infobox modrý a ne oranžový, viz Figma: [https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=6338%3A110937](url)

- [ ] stále progress bar neukazuje správný stav dle Figmy. Screenshot ukazuje aktuální stav:


![Image](https://user-images.githubusercontent.com/98404015/196121985-0033eea3-b46a-452c-baf2-2f80b98bbba1.PNG)

**Comment by KeiShadow** [comment]
@Brambora0  opraveno?

**Comment by Brambora0** [comment]
@KeiShadow ano
