### ISSUE TITLE
Samovyšetření kůže - badges

### ISSUE THREAD

**Issue by jana-pajdlhauserova** [Loono-cz/loono-tasks#60]
Premysliet odmenovanie v pripade samovysetreni kuze - aky typ badgu by sme mohli pouzit.

Related to task #50

**Comment by jana-pajdlhauserova** [comment]
#50

**Comment by jana-pajdlhauserova** [comment]
Po dohode s Deli sme sa rozhodli pre naplecniky/narameniky. Nieco a la prilozene obrazky.







@Deli-Sedlackova Posunieš prosím ďalej na grafické spracovanie.

**Comment by Deli-Sedlackova** [comment]
@KeiShadow Zde jsou hotové ty badge k samovyšetření: 


![Image](https://user-images.githubusercontent.com/98404015/184586043-63d81528-1f29-41ec-bfda-d45d59712431.png)
![Image](https://user-images.githubusercontent.com/98404015/184586042-514c2d12-7332-47f2-856b-32825642dfa2.svg)
