### ISSUE TITLE
Darovani skrze aplikaci - UX

### ISSUE THREAD

**Issue by jana-pajdlhauserova** [Loono-cz/loono-tasks#61]
Doplnit navrh designu o:

- pop up s vyzvou k darovani a CTA + tlacitko s prelinkom na upravu nastavenia notifikacii pre pripad, ze uzivatel nechce aby sa mu notifikacia znovu zobrazovala

- pridat permanentni tlacitko v ramci uzivatelskeho uctu, ktere premsmeruje uzivatele na Darujme.cz

Related to epic: #32

**Comment by jana-pajdlhauserova** [comment]
Navrh layoutu je pripraveny - je potreba este doplnit:

- [ ] Ilustrace - pripravi Betka Davidova (CGI)
- [ ] Texty - headline a kratky popis - pripravi Loono marketing

**Comment by Deli-Sedlackova** [comment]
Texty: 
Delší text (Donation notification)
Otázka: Líbí se ti Preventivka?
Podpoř finančně její rozvoj a staň se součástí mise Loono, která zachraňuje životy.
Tlačítko: Chci přispět
﻿V textu pod tlačítkem prosím jen nahradit "tvého účtu" za "svého účtu".

Kratší text (settings)
Líbí se ti aplikace? Podpoř její rozvoj.

Tlačítko: Chci přispět

**Comment by jana-pajdlhauserova** [comment]
@Deli-Sedlackova 
Texty v návrhu vo Figme sú upravené. Zostáva už len doplniť ilustráciu.
