### ISSUE TITLE
Sekce "Zdrava strava" - UX

### ISSUE THREAD

**Issue by jana-pajdlhauserova** [Loono-cz/loono-tasks#63]
Doplnit vo Figme screeny sekcie O zdravi o cast "Zdravy zivotni styl".

**Comment by Deli-Sedlackova** [comment]
@jana-pajdlhauserova přidávám ikony od grafičky: 

![Image](https://user-images.githubusercontent.com/98404015/184585825-03942ab5-3eeb-4f2a-9076-67ce6a77be71.svg)
![Image](https://user-images.githubusercontent.com/98404015/184585826-d4273674-aefa-40e7-9b8b-6173e19977ad.svg)
![Image](https://user-images.githubusercontent.com/98404015/184585827-97533c08-dd3a-4b46-8ef5-e4a760c4d365.svg)

**Comment by jana-pajdlhauserova** [comment]
Navrh je pripraveny - viz https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15061%3A278874
