### ISSUE TITLE
Při znovu otevření aplikace se účet přestane načítat

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#66]
Při zavření aplikace a jejím opětovném otevření zmizí z obrazovky samovyšetření, avatar, jméno a body a nelze tím pádem ani nic upravovat v settings. Uživatel se musí odhlásit a opětovně přihlásit, aby se mu opět jeho údaje načetly.

**Comment by KeiShadow** [comment]
Taky se mi nepotvrdilo nic takoveho :D @Deli-Sedlackova

**Comment by Deli-Sedlackova** [comment]
Hele tohle se před dvěma týdny stalo uživatelce a jednou za čas se to děje i mně. Bohužel nejsem schopná zreplikovat, kdy se to děje, protože se to neděje pokaždé.
