### ISSUE TITLE
Nelze potvrdit absolvované samovyšetření

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#67]
Uživatel nemůže potvrdit provedené samovyšetření, neumožňuje zakliknout tlačítko "vyšetřil/a jsem se"

**Comment by KeiShadow** [comment]
@Deli-Sedlackova Tohle by melo byt taky opraveno.

**Comment by Deli-Sedlackova** [comment]
Já nejsem schopná to snadno otestovat, nicméně ještě před týdnem to nešlo. @KeiShadow jak jsi testoval?

**Comment by KeiShadow** [comment]
Testoval jsem na devu i produkci, na samovysetreni jsem kliknul a dal ze jsem se vysetril a fungovalo to :D @Deli-Sedlackova 
Jak uz kliknes jednou na vysetril jsem se tak v danem mesici to uz nefunguje :D coz by melo byt ok kdyz je to jednou mesicne :D

**Comment by Deli-Sedlackova** [comment]
@KeiShadow 
Opět přišel bug, že potvrzení samovyšetření nelze zakliknout - viz screenshot: 
Pri samovysetreni varlat zasa tlačidlo síce je ale nefunguje jeho stlačenie (príloha).


![Image](https://user-images.githubusercontent.com/98404015/187148935-7e5fa1b4-f72a-4afd-bb69-30664b2215eb.png)

**Comment by KeiShadow** [comment]
Melo by byt opraveno v test. verzi.
