### ISSUE TITLE
Revize notifikací - BE

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#70]
Je potřeba projít notifikace, zda souhlasí jejich nastavení frekvence s dokumentací. Dokumentace popsána v Epicu: https://github.com/Loono-cz/loono-tasks/issues/55

**Comment by StepanDrozdek** [comment]
@JanaHej 
https://github.com/Loono-cz/loono-tasks/wiki/LOON-394-Push-notification - rozdílný text Check-up visit is coming mezi zadáním a BE

Time je v BE 10:00 (v dokumentaci 8:00), může být kvůli časového posunu (server time vs real)
