### ISSUE TITLE
Při vyhledávání lékaře ze sekce Prevence je uvedená špatná specializace

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#79]
Při prokliku "Nemám lékaře" v kartě prohlídky Oční se v sekci Najít lékaře otevře specializace Praktického lékaře. 
Žádoucí chování by bylo, aby se otevřela příslusná specializace - tzn v případě rozkliku z očního, měl by se v Najít lékaře objevit filtr Očař. 

https://user-images.githubusercontent.com/98404015/187151382-7da4d6a5-aa0c-424c-a5b3-b17a3fa00914.MP4

**Comment by Deli-Sedlackova** [comment]
Toto mi stále neběží, na devu při testování u Kožaře, viz video. Jde o to, že by při rozkliku z jakékoliv specializace měl být v Najít lékaře už rovnou přednastavený filtr dané specializace. V tomto případě tedy Kožař:

Uploading RPReplay_Final1665054680.MP4…

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.306
Mám stále u tohoto zvláštní chování- filtr se mi sice zobrazí na správné specializaci, ale mapa ukazuje stále výsledky všeho a neodpovídají potom popisky u lékařů, viz klip:


https://user-images.githubusercontent.com/98404015/194811324-e066e521-2e63-45d2-9748-8e4cb638777c.MP4

**Comment by Brambora0** [comment]
Je to na pullrequestu https://github.com/Loono-cz/loono/pull/410
