### ISSUE TITLE
Nefunguje dev appka

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#82]
Při otevření dev aplikace, avatar má 0 bodů a badgů, a nezobrazuje se seznam prohlídek, při refreshi to stále ukazuje "Žádné záznamy". Při opětovném přihlášení aplikace píše, že má preventivní prohlídku, zkuste za 5 minut. Viz video

https://user-images.githubusercontent.com/98404015/187397294-35f28c8e-a84c-489c-8fbe-3ef59fc5bf4e.MP4

**Comment by JanaHej** [comment]
Stale nefunguje, viz 

https://user-images.githubusercontent.com/101713252/194015156-f4f273e3-fdfc-4be8-905b-124717d4df3b.mp4

Pravdepodobne se chyba objevuje i na produkci (deli, chovani dnes rano)

jakmile se priojim do dev db zkusm nasdilet podrobnosti o uctu

**Comment by Deli-Sedlackova** [comment]
Nefunguje ani produkční appka - při opětovném přihlášení se zobrazuje jen dokola loading - jak v prevenci tak v Najít lékaře, viz screenshot:


![Image](https://user-images.githubusercontent.com/98404015/194017609-04776106-6195-4cb2-85dd-10fe8b6298ed.PNG)



![Image](https://user-images.githubusercontent.com/98404015/194017615-26fcff83-6046-43df-a1ff-7a6429a92081.PNG)

**Comment by StepanDrozdek** [comment]
Problém od @JanaHej  je fixnutý - poprosil bych o přetestování stávajích chyb (stejná příčina mohla způsobovat vícero chyb)
