### ISSUE TITLE
Skrýt Co s body v nastavení účtu

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#83]
Aktuálně je v aplikaci v nastavení účtu button Co s body, při němž se uživatel proklikne na text ohledně toho, že body připravujeme. Prosím, z kapacitních důvodů odměny za body ještě nebudou přichystané, takže je potřeba toto tlačítko (a tím celou sekci Body) skrýt. 

Related to task https://github.com/Loono-cz/loono-tasks/issues/32

**Comment by janblahacgi** [comment]
Skrýt v žebříčku.

**Comment by KeiShadow** [comment]
toto je opraveno zde ... https://github.com/Loono-cz/loono/pull/367
