### ISSUE TITLE
Nelze vytvorit ucet pomoci appleID

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#86]
Snazim se prihlasit/vytovrit ucet pomoci appleId.

Prihlasit se jako existujici uzivatel nejde, hlasi mi to, ze uzivatel s takovym uctem neexistuje. Pokud se pokusim projit onboardingem a vytvorit novy ucet, objevi se hlaska Neco se nepovedo. Pokud pouziju google ucet, tak registrace probehne v poradku.

device: iPhone SE, iOS 15.6.1

**Comment by smolikjacgi** [comment]
Nyni funguje.

Problem byl z doby, kdy kvuli vyvoji spastne komunikovala aplikace s BE. Ucet se vytvoril ve Firebase, ovsem app s BE nekodakaza spravne komunikovat a zaznam v DB se nevytvoril. FB tedy ma zaznam, ale DB nikoliv - nevytvari se novy zaznam v DB. App se snazi zaznam stahnout - ten ale neexistuje.

Fix je nasledovny: Kontaktuj mne prosim a smazeme ti ucet z FB. Pote si validne vytvoris novy:)
