### ISSUE TITLE
LOON-684 Feedback button zakrývá jméno na homescreen

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono-tasks#9]
Při delším jméně, než je 6 znaků, tak Feedback button zakrývá jméno uživatele v sekci Prevence. Žádoucí chování je, aby button byl výše, než je jméno, viz screenshot

![Image](https://user-images.githubusercontent.com/101713252/176041488-da2c5ebe-acef-4ff9-a01d-bb7e82a87a66.png)

**Comment by KeiShadow** [comment]
Nebude hezčí když se to jméno s body hodí pod profilový obrázek  ? :D

**Comment by ulcdenis** [comment]
Aktuální řešení vypadá takto:

![Image](https://user-images.githubusercontent.com/93252999/194066767-df6a4d09-0397-4789-9535-de34fb47b095.png)

Což za mě stále není optimální...

**Comment by KeiShadow** [comment]
Opraveno v testovaci verzi.

**Comment by Deli-Sedlackova** [comment]
Pořád to není ideální, to jméno mi přijde tentokrát zase moc nízko, je tam zbytečná mezera, viz orbázek. 

![Image](https://user-images.githubusercontent.com/98404015/194715652-74bb3536-995e-4206-944c-1748dcc6aeaa.jpeg)
