### ISSUE TITLE
Dev: Aplikace zobrazuje chybovou hlášku o připojení k internetu

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#92]
Po přihlášení na dev appku aplikace ukazuje chybovou hlášku o tom, že chybí připojení na internet. Zařízení ale připojené je. Verze  0.2.299, iPhone 7.

![Image](https://user-images.githubusercontent.com/98404015/193812458-30cd40cd-b721-4c08-b3db-6aed2ddb18bd.jpg)
https://user-images.githubusercontent.com/98404015/193812459-9b187129-b28b-448c-bc17-9d6d424d8ea4.MOV

**Comment by KeiShadow** [comment]
Mergnuto bude opraveno v nasledujicim buildu.

**Comment by Deli-Sedlackova** [comment]
Bohužel tohle mi pořád neběží, hláška o připojení k internetu se zobrazuje po přihlášení se k účtu a trvá dokud aplikaci nezavřu a znovu neotevřu

**Comment by Deli-Sedlackova** [comment]
@KeiShadow 
Verze 0.2.305
Tato chybová hláška se mi zobrazuje při zakládání nového účtu a jako novému uživateli při zadávání či úpravě poznámky do prohlídky, při úpravě jména či emailu v nastavení účtu

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.306
Chybová hláška se mi v onboardingu stále ukazuje, tentokrát už je při vytváření nového účtu na této stránce: 


![Image](https://user-images.githubusercontent.com/98404015/194810536-75046c0d-e758-40ca-b4af-5efd9ad9e29b.PNG)

**Comment by smolikjacgi** [comment]
@Deli-Sedlackova je prosim stale stejny zpusob k reprodukci chyby 'při zakládání nového účtu...'?

**Comment by smolikjacgi** [comment]
flushbar se docasne nebude zobrazovat

**Comment by smolikjacgi** [comment]
0.2.329
