### ISSUE TITLE
Uživatel si může zadat termín budoucí prohlídky dříve, než je doporučený interval

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#93]
V případě, že si chci upravit termín objednané prohlídky do budoucna ve správném intervalu (např. Zubař, byla jsem v dubnu 2022 a mám objednanou prohlídku na duben 2023), tak když zadám "Upravit datum" a "Změnit termín", tak aplikace umožní zadat libovolný termín, který není v minulosti (tedy např. už říjen 2022).

**Comment by KeiShadow** [comment]
Opraveno bude v testovaci verzi.

**Comment by Deli-Sedlackova** [comment]
V této verzi mi bohužel úprava termínů prohlídek nefunguje vůbec :D, počkám na další verzi a otestuju znovu
