### ISSUE TITLE
Souhlas GDPR + Newsletters - novy uzivatel

### ISSUE THREAD

**Issue by jana-pajdlhauserova** [Loono-cz/loono-tasks#94]
Related issues:

- https://github.com/Loono-cz/loono-tasks/issues/87

**Comment by Deli-Sedlackova** [comment]
Je potřeba přidat na onboarding do registračního formuláře 2 checkboxy.

1) Při dokončení registrace by byl aktivní check-box (povinný) - “Registrací souhlasíš s Podmínkami užívání a Zásadami ochrany osobních údajů a souhlasíš, aby Loono ukládalo informace o tvém zdravotním stavu, které zadáš” (klidně můžete přeformulovat text). Tento checkbox musí být defaultně zaškrtnutý, jinak nepůjde registraci dokončit.
2) Pro newslettery (notifikace na e-mail) by měl být doplněn dobrovolný check-box: “Nechci dostávat od Loono newslettery.” (opět je možné přetextovat). **Tento checkbox by mělo být možné odškrtnout a z toho by se nám měli vytahovat lidi do mailing listu či ne.**

**Comment by Brambora0** [comment]
Přidal jsem do registračního formuláře 3. krok s checkbox pro souhlas s podmínkami používaní a checkbox na newslettery

**Comment by StepanDrozdek** [comment]
Je na pullrequestu - checkbox newsletteru je předáván a uložen do DB

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.305
HIGH
Prosím o změnu textace na: "Chci od Loono dostávat e-mailem..." překlep na konci Loon**o** plus poprosím o lepší zarovnání textu v odstavcích do bloku. Díík!

**Comment by Brambora0** [comment]
Opraveno, je to na pullrequestu https://github.com/Loono-cz/loono/pull/401
