### ISSUE TITLE
Notifikace k sekci O zdraví

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#99]
Je potřeba nastavit jednorázové odeslání notifikací, jejich datum odeslání, textace, apod. je uvedený v tabulce [zde](https://docs.google.com/spreadsheets/d/1Ab1aBPeolB_KNGUcGEIdDNfxWZ5UtMxrr2bluNHuI88/edit?usp=sharing). 

Další naplánovaná notifikace 27.10.2022

AC:
- naplánovat chybějící globální notifikace (cca 10 notifikací)

**Comment by janblahacgi** [comment]
Nastaveno do 31.12.2022

**Comment by janblahacgi** [comment]
Nastaveno do 19.1.2023
